# Generated by Django 4.2.1 on 2023-05-05 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='completed_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='to_do',
            name='created_at',
            field=models.TimeField(default=datetime.time(13, 35, 44, 323567)),
        ),
    ]
